class CfgPatches
{
	class ArG_Core
	{
    addonRootClass="A3_Weapons_F";
		requiredAddons[]=
		{
			"A3_Weapons_F",
			"A3_Weapons_F_Items"
		};
		requiredVersion=0.1;
		units[]={
			"ArG_Gamer_1",
			"ArG_Gamer_2",
			"ArG_Gamer_3",
			"ArG_Gamer_4",
			"ArG_Gamer_5",
			"ArG_Gamer_6",
			"ArG_Gamer_7",
			"ArG_Gamer_8",
			"ArG_Module"
		};
		weapons[]=
		{
		"ArG_MX_F",
		"ArG_MX_F_BLK",
		"ArG_Katiba_F",
		"ArG_Mk20_F",
		"ArG_EBR_F",
		"ArG_Mk200_F",
		"ArG_HE_Grenade_shell",
		"ArG_30Rnd_65x39_BB_02",
		"ArG_30Rnd_65x39_BB_025",
		"ArG_30Rnd_556x45_BB_02",
		"ArG_30Rnd_556x45_BB_025",
		"ArG_20Rnd_762x51_BB_02",
		"ArG_20Rnd_762x51_BB_025",
		"ArG_200Rnd_65x39_cased_Box_BB_02",
		"ArG_200Rnd_65x39_cased_Box_BB_025",
		"ArG_BuzzerBox",
		"ArG_Speaker",
		"Core_Billboard",
		"ArG_muzzle_snds_H",
		"ArG_Blue_Flag",
		"ArG_Red_Flag",
		"ArG_Green_Flag",
		"ArG_Stater_1",
		"ArG_Stater_2",
		"ArG_Revive",
		"ArG_BarGate"
		};
	};
};
